### ISSUE TITLE
Missing standard procedure for backups retrieval 

### ISSUE THREAD

**Issue by filippo-20tab** [20tab/20tab-standard-project#102]
There is no standardized procedure to retrieve backups. My temporary solution was to deploy a forever running image mapped to the backups directory and connect to it. It might give you some clues but it would be nice to have an easier way to do that. I strongly suggest using S3 to store backups.

**Comment by carmelocatalfamo** [comment]
You can access to volume using a deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash-deployment
  namespace: <NAMESPACE>
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bash
  template:
    metadata:
      labels:
        component: bash
    spec:
      volumes:
        - name: postgres-backup-storage
          persistentVolumeClaim:
            claimName: postgres-backup-persistent-volume-claim # PVC name
      containers:
        - name: bash
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: postgres-backup-storage # PVC name volume. Must be equal to spec.template.spec.volumes[0].name
              mountPath: /backup # Backup path
```
